# Generated by Django 4.2.4 on 2023-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0003_product_description_product_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='titleimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
